### ISSUE TITLE
java.lang.UnsupportedClassVersionError: pl/squirrel/classycle/ClassyclePlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ncalexan** [konrad-garus/classycle-gradle-plugin#1]
First, thanks for making this plugin!  I appreciate it.

I'm trying to run this against an Android project.  I get the above error, which I think just means the plugin or the classycle JAR file is compiled with an older `javac` version than I'm using.  Can you confirm?  Is there are a reason to not bump the compilers and release a version that'll accept more `.class` versions?

**Comment by konrad-garus** [comment]
Sorry for late response!

52.0 is Java 8, this exception should only occur if you run it on older Java (like 6 or 7).

**Comment by ncalexan** [comment]
Ah, so I had the inequality reversed.

However, the current state seems backwards.  It would be better to produce the library JAR with the oldest compiler possible, so that it can be used by as many newer compilers as possible, correct?

If that's correct, this ticket should morph to "distribute the plugin compiled with Java 6 or Java 7".

**Comment by konrad-garus** [comment]
It's been a while, but hopefully it's better late than never. I fixed this in 6431c35cd84ac2d394996d29ad6b642a0cd15631 and deployed plugin version 1.2. Thanks a lot!
